name: CI
permissions:
  contents: read

on:
  push:
    branches: ['**']

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check:
    needs: build
    uses: ./.github/workflows/check.yaml

  test-integration:
    needs: [build, check]
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit

  test-e2e:
    needs: [build, check, test-integration]
    uses: ./.github/workflows/test-e2e.yaml
    secrets: inherit

  release:
    if: github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/beta", "refs/heads/dev"]'), github.ref)
    needs: [build, check, test-integration, test-e2e]
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/release.yaml
    secrets:
      VAULT_URL: ${{ secrets.VAULT_URL }}
